name: dialog_flowtter
description: A Flutter implementation of DialogFlow improved. Get your chatbots ready in no time.
version: 0.3.1
homepage: https://github.com/Deimos-Applications/dialog_flowtter
repository: https://github.com/Deimos-Applications/dialog_flowtter
issue_tracker: https://github.com/Deimos-Applications/dialog_flowtter/issues

environment:
    sdk: ">=2.12.0 <3.0.0"
    flutter: ">=1.17.0"

dependencies:
    flutter:
        sdk: flutter
    googleapis_auth: ^1.1.0
    equatable: ^2.0.0
    json_annotation: ^4.0.1
    meta: ^1.3.0
    http: ^0.13.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    effective_dart: ^1.3.0
    build_runner: ^1.11.1
    json_serializable: ^4.0.2
